### ISSUE TITLE
P32: 日志与函数名称不匹配

### ISSUE THREAD

**Issue by fan-chao** [lkimuk/the-book-of-modern-cpp#6]
Hi, 下面这一页（P32）的函数f(A)和f(int)输出的日志感觉不匹配，是不是反了？

![企业微信截图_16867285826959](https://github.com/lkimuk/the-book-of-modern-cpp/assets/10006853/cdfcb3f4-056b-489a-980e-76c626f585ae)

**Comment by lkimuk** [comment]
Hello,

实参类型为`A`，`f(A)`是No conversions，属于标准转换，在没有自定义转换`operator int()`时，`f(int)`是无法匹配到的。

所以这里无误喔~

**Comment by fan-chao** [comment]
> Hello,
> 
> 实参类型为`A`，`f(A)`是No conversions，属于标准转换，在没有自定义转换`operator int()`时，`f(int)`是无法匹配到的。
> 
> 所以这里无误喔~

ok, 那我理解错了。
